---

- get_url:
    url: "https://repo.zabbix.com/zabbix/{{ zbx_version }}/rhel/{{ ansible_facts['distribution_major_version'] }}/x86_64/zabbix-release-{{ zbx_version }}-1.el{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    dest: "/opt/zabbix-release-{{ zbx_version }}-1.el{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"

- yum:
    name: "/opt/zabbix-release-{{ zbx_version }}-1.el{{ ansible_facts['distribution_major_version'] }}.noarch.rpm"
    state: present
